// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auxvbokodyviedbxvomc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1eHZib2tvZHl2aWVkYnh2b21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjEzMzUsImV4cCI6MjA2OTY5NzMzNX0.y2z6y_cy0Oo8ZcskCkwEKdV06VYhYTFcOdOiHvqSW8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});